{
 "title": "CosmicPi Dashboard",
 "description": "Cosmic Pi Data Display",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Event Frequency (per second)",
   "type": "graph",
   "description": "How many events were recorded each second, displayed in time. NB. the query will retrieve 3600 seconds, 1 hour. If you want more time than this you need to change the query.",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Counts per second" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"event_count\" FROM \"CosmicPiV1.8.1_freq\" WHERE $timeFilter ORDER BY DESC LIMIT 3600\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Acceleration (X)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 0 },
   "format": "accMS2",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Accelx\" FROM \"CosmicPiV1.8.1\" GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Magnetometer (X)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Magx\" FROM \"CosmicPiV1.8.1\" GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Acceleration (Y)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 2 },
   "format": "accMS2",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Accely\" FROM \"CosmicPiV1.8.1\" GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Magnetometer (Y)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Magy\" FROM \"CosmicPiV1.8.1\" GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Acceleration (Z)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 4 },
   "format": "accMS2",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Accelz\" FROM \"CosmicPiV1.8.1\" GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Magnetometer (Z)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Magz\" FROM \"CosmicPiV1.8.1\" GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Events (Histogram) per second",
   "type": "graph",
   "description": "Cosmic rays detected by this unit, presented as a histogram",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"event_count\" FROM \"CosmicPiV1.8.1_freq\"  ORDER BY DESC LIMIT 3600",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 6 },
   "format": "humidity",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Hum\" FROM \"CosmicPiV1.8.1\" GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unit Temperature",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 6 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Temp\" FROM \"CosmicPiV1.8.1\" GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 8 },
   "format": "lengthm",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Alt\" FROM \"CosmicPiV1.8.1\" GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 8 },
   "format": "pressurembar",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Press\" FROM \"CosmicPiV1.8.1\" GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "World Map",
   "type": "grafana-worldmap-panel",
   "description": "The location of your detector. NB if the map is blank, it's because your detector doesn't have an internet connection. To connect to the internet, you should log in via SSH and configure your Wi-Fi network via the command \"sudo nano /etc/wpa_supplicant/wpa_supplicant.conf\". Once you have entered your network ID and passphrase, save and restart your Cosmic Pi. It will be accessible via the WiFi network after rebooting, normally at http://cosmicpi (note there is no .com/.net/.anything). ",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"id\",\"geohash\",\"event_count\" FROM \"CosmicPiV1.8.1_freq\" GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Continuous Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Temp\" FROM \"CosmicPiV1.8.1\" ORDER BY DESC LIMIT 3600",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Count rate",
   "type": "singlestat",
   "description": "The count rate for the last second where data was sampled. It should normally be around 2 or 3, with a maximum of 10 and a minimum of 0.",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 10 },
   "format": "hertz",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"event_count\" FROM \"CosmicPiV1.8.1_freq\" ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Device Session ID",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 17, "y": 10 },
   "format": "accMS2",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values from \"CosmicPiV1.8.1\" with key=\"id\" ORDER BY ASC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "About this dashboard",
   "type": "text",
   "gridPos": { "h": 4, "w": 10, "x": 13, "y": 12 },
   "content": "Here is the display of the data from your Cosmic Pi!\nYou can customise the views and way the data is represented, but it's best to do this in a new dashboard. If you lose the current dashboard you can always revert back to the saved version.\nIf you want more information on our project check out http://cosmicpi.org and our github repositories https://github.com/cosmicpi\n"
  }
 ]
}